[package]
name = "FindCom"
version = "0.1.0"
edition = "2021"


[dependencies.winapi]
version = "0.3.9"
features = [
    "combaseapi",
    "objbase",
    "oaidl",
    "wtypesbase",
    "winerror",
    "winnt",
    "coml2api",
    "oleauto"
]

















